

services:
  postgres:
    image: postgres:16-alpine
    container_name: rms_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rms_network

  redis:
    image: redis:alpine
    container_name: rms_redis
    ports:
      - "6379:6379"
    networks:
      - rms_network

networks:
  rms_network:
    driver: bridge

volumes:
  postgres_data:
